

class HW_NOTIFICATION_TIMER_ALIASES(object):
    WAIT_TIMER_UI = 'HWWaitStatusNotificationTimerUI'
    GOTO_TIMER_UI = 'HWGotoStatusNotificationTimerUI'
    FILL_TIMER_UI = 'HWFillStatusNotificationTimerUI'
    WAIT_DESTROY_TIMER_UI = 'WaitDestroyTimerUI'
    WAIT_SECONDARY_TIMER_UI = 'MagnusWaitSecondaryTimerUI'
    FILL_DESTROY_TIMER_UI = 'FillDestroyTimerUI'
    GOTO_DESTROY_TIMER_UI = 'GoToDestroyTimerUI'
    SECONDARY_TIMER_UI = 'MagnusSecondaryTimerUI'
    ICON_VOLOT_READY_SMALL = 'IconVolotReadySmall'
    ICON_VOLOT_READY = 'IconVolotReady'
    ICON_VOLOT_FILL_IN = 'IconVolotFillingIn'
    ICON_VOLOT_FILL_IN_SMALL = 'IconVolotFillingInSmall'
    ICON_VOLOT_FILL_NOT_ACTIVE = 'IconVolotFillingInNotActive'
    ICON_VOLOT_FILL_NOT_ACTIVE_SMALL = 'IconVolotFillingInNotActiveSmall'
    ICON_VOLOT_GOTO = 'TeleportTimerIcon'
    ICON_VOLOT_GOTO_SMALL = 'TeleportTimerIconSmall'
    HW_DEATH_ZONE = 'DearhZoneStatusIconUI'
    HW_PERSONAL_DEATH_ZONE = 'AreaDearhZoneStatusIconUI'
    HW_PERSONAL_DEATH_ZONE_SMALL = 'AreaDearhZoneStatusIconSmallUI'