

class HW_RADIAL_MENU_CONSTS(object):
    HW_COLLECTOR = 'HWCollector'
    HW_COLLECTOR_HELP = 'HWCollectorHelp'
    HW_CAMP = 'HWCamp'
    HW_CAMP_HELP = 'HWCampHelp'
    HW_CANCEL = 'HWNo'
    TARGET_STATE_HW_COLLECTOR = 'hwCollector'
    TARGET_STATE_HW_CAMP = 'hwCamp'
    WHITE_TARGET_STATES = [TARGET_STATE_HW_COLLECTOR, TARGET_STATE_HW_CAMP]