from constants_utils import ConstInjector
from gui.battle_control import battle_constants
from gui.battle_control.controllers import feedback_events
from messenger import m_constants
from races_common.races_constants import BATTLE_EVENT_TYPE

class FEEDBACK_EVENT_ID(battle_constants.FEEDBACK_EVENT_ID, ConstInjector):
    RACES_SHOT = 87
    RACES_BOOST = 88
    RACES_RAMMING = 89
    RACES_SHIELD = 90
    RACES_ELECTRICAL_SHOCK = 91
    RACES_POWER_IMPULSE = 92


class SCH_CLIENT_MSG_TYPE(m_constants.SCH_CLIENT_MSG_TYPE, ConstInjector):
    RACES_STATE = 500
    RACES_LOOT_BOXES_ACCRUAL = 501


_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT = {BATTLE_EVENT_TYPE.RACES_SHOT: FEEDBACK_EVENT_ID.RACES_SHOT, 
   BATTLE_EVENT_TYPE.RACES_BOOST: FEEDBACK_EVENT_ID.RACES_BOOST, 
   BATTLE_EVENT_TYPE.RACES_RAMMING: FEEDBACK_EVENT_ID.RACES_RAMMING, 
   BATTLE_EVENT_TYPE.RACES_SHIELD: FEEDBACK_EVENT_ID.RACES_SHIELD, 
   BATTLE_EVENT_TYPE.RACES_ELECTRICAL_SHOCK: FEEDBACK_EVENT_ID.RACES_ELECTRICAL_SHOCK, 
   BATTLE_EVENT_TYPE.RACES_POWER_IMPULSE: FEEDBACK_EVENT_ID.RACES_POWER_IMPULSE}
_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS = {FEEDBACK_EVENT_ID.RACES_SHOT: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.RACES_BOOST: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.RACES_RAMMING: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.RACES_SHIELD: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.RACES_ELECTRICAL_SHOCK: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.RACES_POWER_IMPULSE: feedback_events._unpackInteger}

def injectClientConstants():
    feedback_events._BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT.update(_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT)
    feedback_events._PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS.update(_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS)