from constants_utils import ConstInjector
from cosmic_event_common.cosmic_constants import BATTLE_EVENT_TYPE
from gui.battle_control import battle_constants
from gui.battle_control.controllers import feedback_events
from personal_missions_constants import CONDITION_ICON
from gui.server_events import cond_formatters
from messenger import m_constants

class FEEDBACK_EVENT_ID(battle_constants.FEEDBACK_EVENT_ID, ConstInjector):
    COSMIC_KILL = 81
    COSMIC_RAMMING = 82
    COSMIC_PICKUP_ABILITY = 83
    COSMIC_ABILITY_HIT = 84
    COSMIC_SHOT = 85
    COSMIC_FRAGMENT_PICKUP = 86
    COSMIC_FRAGMENT_CARRYING = 87
    COSMIC_FRAGMENT_DELIVERING = 88
    COSMIC_KILL_ASSIST = 89
    COSMIC_FRAGMENT_HOLDER_KILL = 90
    COSMIC_EVACUATION = 91


class SCH_CLIENT_MSG_TYPE(m_constants.SCH_CLIENT_MSG_TYPE, ConstInjector):
    COSMIC_DAILY = 400
    COSMIC_EVENT_STATE = 401
    COSMIC_COMPLETED = 402


BATTLE_RESULTS_KEYS = {'cosmicTotalScore': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/SHOT': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/RAMMING': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/KILL': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/KILL_ASSIST': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/ABILITY_PICKUP': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/ABILITY_HIT': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/SHOT': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/RAMMING': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/KILL': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/ABILITY_PICKUP': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/KILL_ASSIST': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/ABILITY_HIT': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/FRAGMENT_HOLDER_KILL': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/FRAGMENT_DELIVERING': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/LAST_OWN_KILLER_ELIMINATIONS_COUNT': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/EVACUATION_SUCCESS': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/EVACUATION': CONDITION_ICON.EXPERIENCE, 
   'cosmicBattleEvent/SCORE_LEADER_HIT_COUNT': CONDITION_ICON.EXPERIENCE, 
   'cosmicAbilitiesUsage/TOTAL': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/FRAGMENT_PICKUP': CONDITION_ICON.EXPERIENCE, 
   'cosmicScore/FRAGMENT_CARRYING': CONDITION_ICON.EXPERIENCE, 
   'cosmicEquipment/2458107': CONDITION_ICON.EXPERIENCE, 
   'cosmicEquipment/2458619': CONDITION_ICON.EXPERIENCE, 
   'cosmicEquipment/2459899': CONDITION_ICON.EXPERIENCE}
_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT = {BATTLE_EVENT_TYPE.COSMIC_KILL: FEEDBACK_EVENT_ID.COSMIC_KILL, 
   BATTLE_EVENT_TYPE.COSMIC_RAMMING: FEEDBACK_EVENT_ID.COSMIC_RAMMING, 
   BATTLE_EVENT_TYPE.COSMIC_PICKUP_ABILITY: FEEDBACK_EVENT_ID.COSMIC_PICKUP_ABILITY, 
   BATTLE_EVENT_TYPE.COSMIC_ABILITY_HIT: FEEDBACK_EVENT_ID.COSMIC_ABILITY_HIT, 
   BATTLE_EVENT_TYPE.COSMIC_SHOT: FEEDBACK_EVENT_ID.COSMIC_SHOT, 
   BATTLE_EVENT_TYPE.COSMIC_FRAGMENT_PICKUP: FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_PICKUP, 
   BATTLE_EVENT_TYPE.COSMIC_FRAGMENT_CARRYING: FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_CARRYING, 
   BATTLE_EVENT_TYPE.COSMIC_FRAGMENT_DELIVERING: FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_DELIVERING, 
   BATTLE_EVENT_TYPE.COSMIC_KILL_ASSIST: FEEDBACK_EVENT_ID.COSMIC_KILL_ASSIST, 
   BATTLE_EVENT_TYPE.COSMIC_FRAGMENT_HOLDER_KILL: FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_HOLDER_KILL, 
   BATTLE_EVENT_TYPE.COSMIC_EVACUATION: FEEDBACK_EVENT_ID.COSMIC_EVACUATION}
_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS = {FEEDBACK_EVENT_ID.COSMIC_KILL: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_RAMMING: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_PICKUP_ABILITY: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_ABILITY_HIT: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_SHOT: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_PICKUP: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_CARRYING: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_DELIVERING: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_KILL_ASSIST: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_FRAGMENT_HOLDER_KILL: feedback_events._unpackInteger, 
   FEEDBACK_EVENT_ID.COSMIC_EVACUATION: feedback_events._unpackInteger}

def injectClientConstants():
    feedback_events._BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT.update(_BATTLE_EVENT_TO_PLAYER_FEEDBACK_EVENT)
    feedback_events._PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS.update(_PLAYER_FEEDBACK_EXTRA_DATA_CONVERTERS)
    cond_formatters.BATTLE_RESULTS_KEYS.update(BATTLE_RESULTS_KEYS)