

class GRINCH_BATTLE_EFFICIENCY_TYPES(object):
    TURRET_DEALT_DAMAGE = 'turretDealtDamage'
    TURRET_DESTROYED = 'turretDestroyed'
    BLIZZARD_CAUSED_DAMAGE = 'blizzardCausedDamage'
    DAMAGED_BY_BLIZZARD = 'damagedByBlizzard'
    DAMAGED_BY_SNOWSTORM = 'damagedBySnowstorm'
    BASE_DEFENDER_BONUS = 'baseDefenderBonus'
    ABILITY_ASSIST_FLARE = 'abilityAssistFlare'
    ABILITY_ASSIST_BLIZZARD = 'abilityAssistBlizzard'
    ABILITY_ASSIST_BUFF = 'abilityAssistBuff'
    PRESENTS_DELIVERY = 'presentsDelivery'
    RAGE = 'rage'
    DAMAGED_BY_DART = 'damagedByDart'
    DART_DAMAGE_CAUSED = 'dartDamageCaused'
    ABILITY_ASSIST_SONAR = 'abilityAssistSonar'
    SONAR_CAUSED_DAMAGE = 'sonarCausedDamage'
    MISSILE_DAMAGE_CAUSED = 'missileDamageCaused'
    MISSILE_DAMAGE_RECEIVED = 'missileDamageReceived'
    SONAR_DAMAGE = 'sonarDamage'