package net.wg.gui.battle.historicalBattles.ribbonsPanel
{
   import net.wg.data.constants.generated.BATTLEATLAS;
   import net.wg.data.constants.generated.BATTLE_EFFICIENCY_TYPES;
   import net.wg.data.constants.generated.HB_DAMAGE_SOURCE_TYPES;
   import net.wg.gui.components.ribbon.constants.RibbonColors;
   import net.wg.gui.components.ribbon.data.DamageSourceSetting;
   import net.wg.gui.components.ribbon.data.RibbonSettingByType;
   import net.wg.gui.components.ribbon.data.RibbonSettings;
   
   public class HBRibbonSettings extends RibbonSettings
   {
       
      
      public function HBRibbonSettings(param1:String, param2:String)
      {
         super(param1,param2);
      }
      
      override protected function atlasInit() : void
      {
         super.atlasInit();
         var _loc1_:String = RibbonColors.GREEN;
         var _loc2_:String = RibbonColors.RED;
         var _loc3_:String = RibbonColors.PURPLE;
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.DAMAGE_BY_HB_MINEFIELD] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_MINE_FIELD_HB,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_MINE_FIELD_HB,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.BOMBERS] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_AIRSTRIKE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_AIRSTRIKE,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.RECEIVED_BOMBERS_DAMAGE] = new RibbonSettingByType(_loc2_,BATTLEATLAS.AIRSTRIKE_ENEMY,_loc3_,BATTLEATLAS.AIRSTRIKE_ENEMY_BLIND,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.ARTILLERY] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.DAMAGE_BY_ARTILLERY_ROCKET] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.DAMAGE_BY_ARTILLERY_MORTAR] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_ARTILLERY,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.DAMAGE_BY_BOMBERCAS] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_BOMBERCAS,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_BOMBERCAS,3);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.HB_DEATH_ZONE] = new RibbonSettingByType(_loc2_,BATTLEATLAS.ARTILLERY_ENEMY,_loc3_,BATTLEATLAS.ARTILLERY_ENEMY_BLIND,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.HB_PERSONAL_DEATH_ZONE] = new RibbonSettingByType(_loc2_,BATTLEATLAS.ARTILLERY_ENEMY,_loc3_,BATTLEATLAS.ARTILLERY_ENEMY_BLIND,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.HEAL_VEHICLE_APPLIED] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.HEAL_SELF_VEHICLE_APPLIED] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.TOTAL_VEHICLES_HEAL_APPLIED] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,_loc1_,BATTLEATLAS.RIBBONS_HEALTH_REGENERATION,1);
         RIBBON_TYPES_MAP[BATTLE_EFFICIENCY_TYPES.DAMAGE_BY_HB_TACTICAL_MINE] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_MINE_FIELD_HB,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE_MINE_FIELD_HB,3);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.LIGHT_TANK_ELITE] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_LIGHT_TANK_ELITE16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.MEDIUM_TANK_ELITE] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_MEDIUM_TANK_ELITE16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.HEAVY_TANK_ELITE] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_HEAVY_TANK_ELITE16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.AT_SPG_ELITE] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_AT_SPG_ELITE16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.SPG_ELITE] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_SPG_ELITE16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.BOSS] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_BOSS16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.AIMER] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_AIMER16X16);
         DAMAGE_SOURCE_MAP[HB_DAMAGE_SOURCE_TYPES.RUNNER] = new DamageSourceSetting(BATTLEATLAS.WHITE_ICON_RUNNER16X16);
      }
      
      override protected function init() : void
      {
         super.init();
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.LIGHT_TANK_ELITE] = -2;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.MEDIUM_TANK_ELITE] = -1;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.HEAVY_TANK_ELITE] = 0;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.AT_SPG_ELITE] = -1;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.SPG_ELITE] = -1;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.BOSS] = 0;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.AIMER] = 0;
         ICON_X_PADDINGS[HB_DAMAGE_SOURCE_TYPES.RUNNER] = -1;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.LIGHT_TANK_ELITE] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.MEDIUM_TANK_ELITE] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.HEAVY_TANK_ELITE] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.AT_SPG_ELITE] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.SPG_ELITE] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.BOSS] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.AIMER] = 11;
         ICON_Y_PADDINGS[HB_DAMAGE_SOURCE_TYPES.RUNNER] = 11;
      }
   }
}
