

class ANIMATION_TYPES(object):
    NONE = 0
    MOVE_ORANGE_BAR_UP = 1
    MOVE_ORANGE_BAR_DOWN = 2
    MOVE_GREEN_BAR_UP = 4
    MOVE_GREEN_BAR_DOWN = 8
    SHOW_COUNTER_GREEN = 16
    SHOW_COUNTER_ORANGE = 32
    CENTER_COUNTER = 64
    GREEN_GLOW_SHOW = 128
    GREEN_GLOW_HIDE = 256
    FILL_PARTIALLY = 512
    DARK_COLOR_TRANSFORM = 1024