

class CONSUMABLES_PANEL_SETTINGS(object):
    DEFAULT_SETTINGS_ID = 0
    BIG_SETTINGS_ID = 1
    BATTLE_ROYALE_SETTINGS_ID = 2
    GLOW_ID_GREEN = 0
    GLOW_ID_ORANGE = 1
    GLOW_ID_GREEN_SPECIAL = 2