

class CROSSHAIR_CONSTANTS(object):
    INVISIBLE = 0
    VISIBLE_NET = 1
    VISIBLE_AMMO_COUNT = 2
    VISIBLE_ALL = 3
    ART_SHOT_INDICATOR_NOT_ACTIVE = 0
    ART_SHOT_INDICATOR_ACTIVE = 1
    ART_SHOT_INDICATOR_EMPTY_SHELL = 2