

class CROSSHAIR_CASSETTE_TYPES(object):
    NO_CASSETTE = 0
    CASSETTE = 1
    AUTOLOADER = 2
    MULTIPLE_BARREL_CASSETTE = 3
    MULTIPLE_BARREL_AUTOLOADER = 4
    CASSETTE_TYPES = [NO_CASSETTE, CASSETTE, AUTOLOADER, MULTIPLE_BARREL_CASSETTE, MULTIPLE_BARREL_AUTOLOADER]
    MULTIPLE_BARREL_TYPES = [MULTIPLE_BARREL_CASSETTE, MULTIPLE_BARREL_AUTOLOADER]