

class GIFTSYTEM_CONSTANTS(object):
    PLAYER_BANNED = 'playerBanned'
    PLAYER_ALREADY_RECEIVED_GIFT = 'playerAlreadyReceivedGift'
    PLAYER_IN_BLACK_LIST = 'playerInBlackList'
    PLAYER_BLOCKED_REASONS = [PLAYER_BANNED, PLAYER_ALREADY_RECEIVED_GIFT, PLAYER_IN_BLACK_LIST]