

class KEYBOARD_KEYS(object):
    FORWARD = 'forward'
    BACKWARD = 'backward'
    LEFT = 'left'
    RIGHT = 'right'
    AUTO_ROTATION = 'auto_rotation'
    FORWARD_CRUISE = 'forward_cruise'
    BACKWARD_CRUISE = 'backward_cruise'
    FIRE = 'fire'
    LOCK_TARGET = 'lock_target'
    LOCK_TARGET_OFF = 'lock_target_off'
    ALTERNATE_MODE = 'alternate_mode'
    RELOAD_PARTIAL_CLIP = 'reloadPartialClip'
    SHOW_RADIAL_MENU = 'showRadialMenu'
    HIGHLIGHT_LOCATION = 'highlightLocation'
    HIGHLIGHT_TARGET = 'highlightTarget'
    PUSH_TO_TALK = 'pushToTalk'
    VISIBLE = 'visible'
    SHOW_HUD = 'showHUD'
    SHOW_EX_PLAYER_INFO = 'showExPlayerInfo'
    TOGGLE_PLAYER_PANEL_MODES = 'togglePlayerPanelModes'
    STOP_FIRE = 'stop_fire'