

class POI_CONSTS(object):
    POI_TYPE_ARTILLERY = 1
    POI_TYPE_RECON = 2
    POI_TYPE_SMOKE = 3
    POI_TYPE_MINEFIELD = 4
    POI_STATUS_ACTIVE = 0
    POI_STATUS_CAPTURING = 1
    POI_STATUS_COOLDOWN = 2