

class RESEARCH_COUNTER_STATES(object):
    RESEARCH_NOT_AVAILABLE = 'none'
    RESEARCH_MODULE_AVAILABLE = 'researchModuleAvailable'
    RESEARCH_MODULE_AVAILABLE_FORCED = 'researchModuleAvailableForced'
    RESEARCH_VEHICLE_AVAILABLE = 'researchVehicleAvailable'
    RESEARCH_VEHICLE_AVAILABLE_FORCED = 'researchVehicleAvailableForced'
    TRANSITION_VEHICLE_TO_MODULE = 'vehToModule'
    ALL = [RESEARCH_NOT_AVAILABLE, RESEARCH_MODULE_AVAILABLE, RESEARCH_MODULE_AVAILABLE_FORCED, RESEARCH_VEHICLE_AVAILABLE, RESEARCH_VEHICLE_AVAILABLE_FORCED]