

class ROCKET_ACCELERATOR_INDICATOR(object):
    PREPARING = 'preparing'
    ACTIVE = 'active'
    READY = 'ready'
    DISABLE = 'disable'
    ROCKET_ACCELERATOR_INDICATOR_STATE = [PREPARING, ACTIVE, READY, DISABLE]