

class SEASONS_CONSTANTS(object):
    SUMMER_INDEX = 0
    WINTER_INDEX = 1
    DESERT_INDEX = 2
    SUMMER = 'summer'
    WINTER = 'winter'
    DESERT = 'desert'
    SEASONS = [SUMMER, WINTER, DESERT]
    INDICES = [SUMMER_INDEX, WINTER_INDEX, DESERT_INDEX]