

class SIEGE_MODE_CONSTS(object):
    HYDRAULIC_CHASSIS_TYPE = 'hydraulicChassisType'
    TURBOSHAFT_ENGINE_TYPE = 'turboshaftEngineType'
    SIEGE_MODE_TYPES = [HYDRAULIC_CHASSIS_TYPE, TURBOSHAFT_ENGINE_TYPE]