

class SIEGE_MODE_CONSTS(object):
    HYDRAULIC_CHASSIS_TYPE = 'hydraulicChassisType'
    TURBOSHAFT_ENGINE_TYPE = 'turboshaftEngineType'
    TRACK_WITHIN_TRACK_TYPE = 'trackWithinTrackType'
    TWIN_GUN_TYPE = 'twinGunType'
    SIEGE_MODE_TYPES = [HYDRAULIC_CHASSIS_TYPE, TURBOSHAFT_ENGINE_TYPE, TRACK_WITHIN_TRACK_TYPE, TWIN_GUN_TYPE]