

class VEHICLE_SELECTOR_CONSTANTS(object):
    VISIBLE_NONE = 0
    VISIBLE_LEVEL = 1
    VISIBLE_NATION = 2
    VISIBLE_VEHICLE_TYPE = 4
    VISIBLE_IS_MAIN = 8
    VISIBLE_COMPATIBLE_ONLY = 16
    VISIBLE_ALL = 31