from gui.shared.system_factory import registerAmmunitionPanelView
from gui.impl.lobby.tank_setup.comp7.ammunition_panel import Comp7AmmunitionPanelView
registerAmmunitionPanelView(Comp7AmmunitionPanelView)