from chat_commands_consts import BATTLE_CHAT_COMMAND_NAMES, MarkerType, DefaultMarkerSubType, INVALID_MARKER_SUBTYPE
from gui.Scaleform.genConsts.RADIAL_MENU_CONSTS import RADIAL_MENU_CONSTS
from gui.Scaleform.daapi.view.battle.shared.radial_menu import Shortcut, _MARKERS_TYPE_TO_SUBTYPE_MAP, RadialMenu
from gui.Scaleform.locale.INGAME_HELP import INGAME_HELP
from halloween.gui.scaleform.genConsts.HW_RADIAL_MENU_CONSTS import HW_RADIAL_MENU_CONSTS
REGULAR_BOTTOM_STATIC_SHORTCUTS = (
 Shortcut(title=INGAME_HELP.RADIALMENU_RELOADINGGUN, action=BATTLE_CHAT_COMMAND_NAMES.RELOADINGGUN, icon=RADIAL_MENU_CONSTS.RELOAD, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_THIRD),
 Shortcut(title=INGAME_HELP.RADIALMENU_HELPME, action=BATTLE_CHAT_COMMAND_NAMES.SOS, icon=RADIAL_MENU_CONSTS.SOS, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_FOURTH))
REGULAR_UPPER_STATIC_SHORTCUTS = (
 Shortcut(title=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, action=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, icon=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_FIFTH),
 Shortcut(title=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, action=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, icon=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.EMPTY_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_SECOND),
 Shortcut(title='#halloween.halloween_battle:radialMenu/move_to_soul_collector', action=BATTLE_CHAT_COMMAND_NAMES.MOVING_TO_TARGET_POINT, icon=HW_RADIAL_MENU_CONSTS.HW_COLLECTOR, groups=[
  HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_COLLECTOR], bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_FIRST),
 Shortcut(title='#halloween.halloween_battle:radialMenu/attention_here', action=BATTLE_CHAT_COMMAND_NAMES.MOVE_TO_TARGET_POINT, icon=HW_RADIAL_MENU_CONSTS.HW_COLLECTOR_HELP, groups=[
  HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_COLLECTOR], bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_SIXTH),
 Shortcut(title='#halloween.halloween_battle:radialMenu/move_to_camp', action=BATTLE_CHAT_COMMAND_NAMES.MOVING_TO_TARGET_POINT, icon=HW_RADIAL_MENU_CONSTS.HW_CAMP, groups=[
  HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_CAMP], bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_FIRST),
 Shortcut(title='#halloween.halloween_battle:radialMenu/attention_here', action=BATTLE_CHAT_COMMAND_NAMES.MOVE_TO_TARGET_POINT, icon=HW_RADIAL_MENU_CONSTS.HW_CAMP_HELP, groups=[
  HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_CAMP], bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_SIXTH))
_CAN_CANCEL_REPLY_SHORTCUT = Shortcut(title='#halloween.halloween_battle:radialMenu/cancel', action=BATTLE_CHAT_COMMAND_NAMES.CANCEL_REPLY, icon=HW_RADIAL_MENU_CONSTS.HW_CANCEL, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=RADIAL_MENU_CONSTS.ELEMENT_INDEX_FIRST)
_MARKERS_TYPE_TO_SUBTYPE_MAP.update({MarkerType.TARGET_POINT_MARKER_TYPE: {DefaultMarkerSubType.ALLY_MARKER_SUBTYPE: HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_COLLECTOR, 
                                         DefaultMarkerSubType.ENEMY_MARKER_SUBTYPE: HW_RADIAL_MENU_CONSTS.TARGET_STATE_HW_CAMP, 
                                         INVALID_MARKER_SUBTYPE: RADIAL_MENU_CONSTS.TARGET_STATE_DEFAULT}})

class HalloweenRadialMenu(RadialMenu):
    _CMD_CHAT_SHORTCUT_CONTEXT_COMMAND = (
     BATTLE_CHAT_COMMAND_NAMES.DEFEND_BASE, BATTLE_CHAT_COMMAND_NAMES.ATTACK_BASE,
     BATTLE_CHAT_COMMAND_NAMES.HELPME, BATTLE_CHAT_COMMAND_NAMES.ATTENTION_TO_POSITION,
     BATTLE_CHAT_COMMAND_NAMES.ATTACK_OBJECTIVE, BATTLE_CHAT_COMMAND_NAMES.DEFEND_OBJECTIVE,
     BATTLE_CHAT_COMMAND_NAMES.ATTACK_ENEMY, BATTLE_CHAT_COMMAND_NAMES.REPLY,
     BATTLE_CHAT_COMMAND_NAMES.CANCEL_REPLY, BATTLE_CHAT_COMMAND_NAMES.MOVE_TO_TARGET_POINT)
    _CMD_CHAT_SHORTCUT_CONTEXT_COMMIT = (
     BATTLE_CHAT_COMMAND_NAMES.DEFENDING_BASE, BATTLE_CHAT_COMMAND_NAMES.ATTACKING_BASE,
     BATTLE_CHAT_COMMAND_NAMES.ATTACKING_OBJECTIVE, BATTLE_CHAT_COMMAND_NAMES.DEFENDING_OBJECTIVE,
     BATTLE_CHAT_COMMAND_NAMES.ATTACKING_ENEMY_WITH_SPG, BATTLE_CHAT_COMMAND_NAMES.ATTACKING_ENEMY,
     BATTLE_CHAT_COMMAND_NAMES.SUPPORTING_ALLY, BATTLE_CHAT_COMMAND_NAMES.SPG_AIM_AREA,
     BATTLE_CHAT_COMMAND_NAMES.GOING_THERE, BATTLE_CHAT_COMMAND_NAMES.MOVING_TO_TARGET_POINT)
    _ALL_TARGET_STATES = RADIAL_MENU_CONSTS.ALL_TARGET_STATES + HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES

    def _initShortCuts(self):
        super(HalloweenRadialMenu, self)._initShortCuts()
        for shotCut in REGULAR_BOTTOM_STATIC_SHORTCUTS:
            for shotCutGroup in shotCut.groups:
                if shotCutGroup not in self.bottomShortcutSets:
                    self.bottomShortcutSets[shotCutGroup] = list()
                self.bottomShortcutSets[shotCutGroup].append(shotCut)

        for shotCut in REGULAR_UPPER_STATIC_SHORTCUTS:
            for shotCutGroup in shotCut.groups:
                if shotCutGroup not in self.upperShortcutSets:
                    self.upperShortcutSets[shotCutGroup] = list()
                self.upperShortcutSets[shotCutGroup].append(shotCut)

    def _getCanReplayShortcut(self, shortcut, canReplyAction):
        if shortcut.action == BATTLE_CHAT_COMMAND_NAMES.MOVING_TO_TARGET_POINT:
            return Shortcut(title='#halloween.halloween_battle:radialMenu/confirm', action=canReplyAction, icon=RADIAL_MENU_CONSTS.YES, groups=HW_RADIAL_MENU_CONSTS.WHITE_TARGET_STATES, bState=RADIAL_MENU_CONSTS.NORMAL_BUTTON_STATE, indexInGroup=shortcut.indexInGroup)
        return super(HalloweenRadialMenu, self)._getCanReplayShortcut(shortcut, canReplyAction)

    def _getCanCancelReplyShortcut(self):
        return _CAN_CANCEL_REPLY_SHORTCUT