from gui.battle_control.controllers.appearance_cache_ctrls.default_appearance_cache_ctrl import DefaultAppearanceCacheController

class FLAppearanceCacheController(DefaultAppearanceCacheController):
    pass