from fun_random.gui.game_control.awards_controller import FunProgressionQuestsHandler, FunRandomLootBoxAutoOpenHandler
from gui.shared.system_factory import registerAwardControllerHandler

def registerFunRandomAwardControllers():
    registerAwardControllerHandler(FunProgressionQuestsHandler)
    registerAwardControllerHandler(FunRandomLootBoxAutoOpenHandler)